name: Build Panda Reader APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip Project
        run: |
          unzip legado-master.zip -d ./unpacked
          mv ./unpacked/* ./
          rm legado-master.zip

      # 关键修复点：添加 distribution 参数
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # 或 'zulu'/'corretto'

      - name: Grant Gradle Permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v3
        with:
          name: PandaReader-APK
          path: app/build/outputs/apk/debug/app-debug.apk
