name: Build Panda Reader APK
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 防止长时间卡住

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 解压项目（适配您的 legado-master.zip）
      - name: Unzip Project
        run: |
          unzip -q legado-master.zip -d ./unpacked
          mv ./unpacked/* ./
          rm -rf legado-master.zip unpacked
          ls -R  # 打印目录结构确认

      # 3. 设置Java环境（修复distribution缺失问题）
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # 必须参数
          cache: 'gradle'

      # 4. 修复权限并编译
      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      # 5. 上传APK（升级到v4解决下载问题）
      - uses: actions/upload-artifact@v4
        with:
          name: PandaReader-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 3
