name: Build Panda Reader APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 1. 检出代码（强制清理旧文件）
      - uses: actions/checkout@v4
        with:
          clean: true

      # 2. 解压并验证文件结构
      - name: Unzip and Validate
        run: |
          unzip -o legado-master.zip -d ./unpacked
          mv ./unpacked/* ./
          ls -R  # 打印完整目录结构
          [ -f gradlew ] || { echo "Error: gradlew missing!"; exit 1; }

      # 3. 设置Java环境（明确指定版本和发行版）
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # 4. 增加内存限制（避免OOM）
      - name: Build APK with Debug Info
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --info -Dorg.gradle.jvmargs="-Xmx2g"

      # 5. 上传APK（严格校验文件存在性）
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: PandaReader-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
