name: Build APK
on: [push]
permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip Project
        run: |
          unzip legado-master.zip -d ./unpacked
          mv ./unpacked/* ./
          rm legado-master.zip

      - uses: actions/setup-java@v3
        with:
          java-version: '17'

      - run: chmod +x gradlew && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4  # 关键修改点
        with:
          name: PandaReader-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error  # 严格检查APK是否存在
